service: aws-apollo-lambda
provider:
  name: aws
  runtime: nodejs12.x
functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: src/graphql.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
    environment:
      STAGE: dev

custom:
  serverless-offline:
    httpPort: 3000
    port: 3000
    noPrependStageInUrl: true

plugins:
  - serverless-offline
  - serverless-plugin-typescript
